# 1. Your task in this problem is to write a program to determine whether a given number is an Armstrong number. An n-digit number that equals the sum of its digits each raised to the power of n is called an Armstrong number.

n=input()
summ=0
l=len(n)
for i in range(l):
    numm=int(n[i])**l
    summ+=numm

if summ==int(n):
    print("Armstrong number")
else:
    print("Not an armstrong number")

# 2.Your task in this problem is to write a program that prints all prime numbers smaller than or equal to a given number N

def isprime(i):
    if i<=1:
        return 0
    for k in range(2,i):
        if i%k==0:
            return 0
    return 1 
n=int(input())
for i in range(2,n+2):
    if i<=n and isprime(i):
        print(i,end=",")

# 3.Your task in this problem is to write a program to find the Greatest Common Divisor (GCD) of two given numbers, which is the largest number that divides both numbers exactly. The GCD is also known as the Highest Common Factor (HCF) or the greatest common denominator.

n1, n2 = map (int,input().split())

for i in range (1,n1+1):
    if n1%i==0 and n2%i==0:
        ans =i
print(ans)

# 4.Your task in this problem is to find the number of pentagonal numbers Pn (where n < N) such that the difference or sum of two pentagonal numbers Pn and Pn-K is also a pentagonal number.

# Pentagonal numbers are generated by the formula:

# Pn = n (3n − 1) / 2

import math


def is_pentagonal(x):
    if x <= 0:
        return False
    n = (1 + math.sqrt(1 + 24 * x)) / 6
    return n.is_integer()

# Input
N = int(input())
K = int(input())

# Generate all pentagonal numbers up to N
pent = [n * (3 * n - 1) // 2 for n in range(1, N + 1)]

count = 0

# Check for all pairs (Pn, Pn-K)
for n in range(K, N):
    Pn = pent[n - 1]
    Pk = pent[n - K - 1]

    diff = Pn - Pk
    summ = Pn + Pk

    # Check if either sum or difference is pentagonal
    if is_pentagonal(diff) or is_pentagonal(summ):
        count += 1

print(count)


# 5.Your task is to write a program to determine whether the number is a pandigital number or not.

# A pandigital number is a number that contains all digits from 1 to N, where N is the number of digits in the number itself. For example, the number 123 is a 3-digit pandigital number as it contains the digits 1, 2, and 3.

num=input()
digits = set(num)


required = set(str(i) for i in range(1, len(num)+1))

if digits == required:
    print("Yes")
else:
    print("No")

# 6.Your task is to write a program to determine whether the number is an ugly number or not.

# An ugly number is a number whose only prime factors are 2, 3, or 5. The first few ugly numbers are 1, 2, 3, 4, 5, 6, 8, 9, 10, and so on.

n = int(input())

if n == 0:
    print("no")
else:
    for p in [2, 3, 5]:
        while n % p == 0:
            n //= p

    if n == 1:
        print("yes")
    else:
        print("no")


# 7.Your task is to find and count how many duplicate pairs exist in an array input. A duplicate pair is when two numbers in the array are identical and are located at different positions in the array.

n = int(input())
arr = list(map(int, input().split()))

count = 0

for i in range(n):
    for j in range(i+1, n):
        if arr[i] == arr[j]:
            count += 1

print(count)


# 8.You're task is to write a program to find the largest K-digit number from a given string of digits. You are provided a string s consisting of digits and an integer K. Your task is to find and print the largest number that can be formed by K consecutive digits from the string.

s,k=input().split()
newk=int(k)
Final=0
for i in range(len(s)):
    summ=int(s[i:i+newk])
    if summ>Final:
        Final=summ

print(Final)

# 9.Your task is to write a program to calculate the largest product of K consecutive digits in a given numeric series.

# Input
n = int(input())         # number of consecutive digits
num_str = input().strip()  # the number string

max_product = 0

# Loop through each possible consecutive segment
for i in range(len(num_str) - n + 1):
    product = 1
    # Calculate product of n consecutive digits
    for j in range(i, i + n):
        product *= int(num_str[j])
    # Update max if needed
    if product > max_product:
        max_product = product

print(max_product)

# 10.Your task is to write a program that takes a positive integer as input and prints the sum of its digits.

n=input()
total=0
for i in range(len(n)):
    new=int(n[i])
    total+=new
print(total)

# 11.You are given a sum s and a number of digits d. Your task is to find the largest number possible with d digits such that the sum of its digits equals s. If the given sum or number of digits does not meet the constraints, or if it is impossible to create such a number, print -1.

s, d = map(int, input().split())

# If impossible (sum too big or too small)
if s > 9 * d or s <= 0 or d <= 0:
    print(-1)
else:
    result = ""

    for _ in range(d):
        if s >= 9:
            result += "9"
            s -= 9
        else:
            result += str(s)
            s = 0

    print(result)


# 12.Your task is to write a program that takes an integer num as input and repeatedly adds all its digits until the result has only one digit, then return that single-digit result.

n=int(input())
summ=0
if n<10:
    print(n)
else:
    print(n%9)

# 13.Your task is to write a program that prints the square of each digit of a given integer in reverse order, with spaces between the squares.

num = input()

# Reverse the digits
num = num[::-1]

# Print square of each digit
for d in num:
    print(int(d)**2, end=" ")


# 14.Your task is to write a program that takes a positive integer num consisting of exactly four digits as input. Split num into two new integers, new1 and new2, by using the digits found in num. Leading zeros are allowed in new1 and new2, and all the digits found in num must be used. Your task is to print the minimum sum possible from new1 and new2.


n=int(input())
digits=sorted(str(n))
new1=int(digits[0]+digits[2])
new2=int(digits[1]+digits[3])
print(new1+new2)


# 15.Your task is to write a program that prints the frequency of each digit in a given number. The output should display the count of each digit in the given number.


num = input()

freq = {}

for d in num:
    freq[d] = freq.get(d, 0) + 1

for digit in sorted(freq.keys()):
    print(f"{digit}:{freq[digit]}")


# 16.Your task is to write a program that finds the smallest number possible with a given sum s and a specified number of digits d. The program should print the smallest number that can be formed with exactly d digits such that the sum of its digits equals s. If it is not possible to form such a number, print "Not possible"

d = int(input())
s = int(input())

# check impossible
if s > 9*d or s < 1:
    print("Not possible")
else:
    digits = [0] * d

    # reserve 1 for first digit
    s -= 1

    # fill from last digit
    for i in range(d-1, 0, -1):
        add = min(9, s)
        digits[i] = add
        s -= add

    # put remaining sum + reserved 1 in first digit
    digits[0] = 1 + s

    print("Smallest number -", "".join(map(str, digits)))


# 17.Your task is to write a program that takes a number as input and prints each of its digits in words. If the number consists of multiple digits, print the digits in reverse order.

num = input()

words = ["zero","one","two","three","four","five","six","seven","eight","nine"]

# Reverse the number
num = num[::-1]

# Print each digit in words
for d in num:
    print(words[int(d)], end=" ")

# 18.Your task is is to write a program to take an input integer n, find all single-digit numbers (from 1 to 9) such that when raised to the power of n, the resulting number has exactly n digits. Output these numbers in ascending order.

n = int(input())

for i in range(1, 10):
    value = i ** n
    if len(str(value)) == n:
        print(value)


# 19.Your task is to write a program that takes two input numbers a and b representing a fraction a/b (where a < b). The program should print all the reduced forms of the given fraction in a single line. If the input fraction is already in its most reduced form, print -1.


from math import gcd

def all_reduced_forms(a, b):
    forms = []
    for div in range(2, min(a, b)+1):
        if a % div == 0 and b % div == 0:
            forms.append(f"{a//div}/{b//div}")
    return forms

def solve(a, b):
    if gcd(a, b) == 1:
        print(-1)
        return
    results = all_reduced_forms(a, b)
    print(' '.join(results))

a, b = map(int, input().split())
solve(a, b)


# 20.Your task is to write a program to check if the given two numbers can form a proper fraction. Additionally, if the fraction is proper, reduce it to its lowest form and print the reduced fraction. If the fraction is improper, convert it to a mixed fraction and print the result.

import math

num, den = map(int, input().split())

# reduce the fraction
g = math.gcd(num, den)
num //= g
den //= g

if num < den:
    # proper fraction
    print("Proper", f"{num}/{den}")
else:
    # improper → mixed
    whole = num // den
    rem = num % den

    if rem == 0:
        print("Improper", whole)
    else:
        print("Improper", whole, f"{rem}/{den}")


# 21.Selection Sort
# Selection sort in Python
def selectionSort(arr, size):
   # write your code here
   for i in range(size-1):
      mini=i
      for j in range(i+1,size):
         if arr[j]<arr[mini]:
            arr[mini],arr[j]=arr[j],arr[mini]

          
   return arr

size=int(input())
data=list(map(int, input().split()))[:size]

selectionSort(data, size)
print(*data)

# 22.Insertion sort
def insertionSort(array):
    for i in range(1, len(array)):
        key = array[i]
        j = i - 1
        
        while j >= 0 and array[j] > key:
            array[j + 1] = array[j]
            j -= 1
        array[j + 1] = key
    return

# Take input from the user
n = int(input())
array = list(map(int, input().split()))[:n]

# Sort the array using insertion sort
insertionSort(array)

# Print the sorted array
print(*array)


# 23.Bubble Sort

def bubbleSort(arr):
    n = len(arr)
    for i in range(n):
        for j in range(0, n - i - 1):
            if arr[j]>arr[j + 1]:
                arr[j],arr[j+1] = arr[j+1],arr[j]
    return


# Driver code to test the bubbleSort function
if __name__ == "__main__":
    # Take input from the user
    size = int(input())
    data = list(map(int, input().split()))[:size]

    # Sort the array using bubble sort
    bubbleSort(data)

    # Print the sorted array
    for i in range(len(data)):
        print("%d" % data[i], end=" ")

# 24. Merge sort


# MergeSort in Python

def mergeSort(array):
    if len(array) > 1:
        mid = len(array) // 2
        left = array[:mid]
        right = array[mid:]

        # Sort the two halves
        mergeSort(left)
        mergeSort(right)

        # Merge the sorted halves
        i = j = k = 0

        # Compare elements and merge
        while i < len(left) and j < len(right):
            if left[i] < right[j]:
                array[k] = left[i]
                i += 1
            else:
                array[k] = right[j]
                j += 1
            k += 1

        # If elements left in left array
        while i < len(left):
            array[k] = left[i]
            i += 1
            k += 1

        # If elements left in right array
        while j < len(right):
            array[k] = right[j]
            j += 1
            k += 1

# Print the array
def printList(array):
    for i in range(len(array)):
        print(array[i], end=" ")
    print()

# Driver program
if __name__ == '__main__':
    # Get the input array size and elements from the user
    size = int(input())
    data = list(map(int, input().split()[:size]))

    # Call the mergeSort function to sort the array
    mergeSort(data)

    # Print the sorted array
    printList(data)


# 25.Quick Sort

def quickSort(arr, low, high):

    def partition(arr, low, high):
        pivot = arr[high]          # last element as pivot
        i = low - 1

        for j in range(low, high):
            if arr[j] < pivot:
                i += 1
                arr[i], arr[j] = arr[j], arr[i]   # swap

        arr[i + 1], arr[high] = arr[high], arr[i + 1]
        return i + 1

    if low < high:
        pi = partition(arr, low, high)
        quickSort(arr, low, pi - 1)   # left part
        quickSort(arr, pi + 1, high)  # right part

    # write your code here
    return

# Function to print an array
def printArray(arr):
    for i in range(len(arr)):
        print(arr[i], end=" ")
    print()


# Driver code
if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()[:n]))

    quickSort(arr, 0, n - 1)
    printArray(arr)
